use crate::*;
use citationberg_rs;
use js_sys::*;
use wasm_bindgen::prelude::*;
use web_sys::*;

#[wasm_bindgen]
#[derive(Copy, Clone, Debug)]
pub enum Kind {
    Article,
    ArticleJournal,
    ArticleMagazine,
    ArticleNewspaper,
    Bill,
    Book,
    Broadcast,
    Chapter,
    Classic,
    Collection,
    Dataset,
    Document,
    Entry,
    EntryDictionary,
    EntryEncyclopedia,
    Event,
    Figure,
    Graphic,
    Hearing,
    Interview,
    LegalCase,
    Legislation,
    Manuscript,
    Map,
    MotionPicture,
    MusicalScore,
    Pamphlet,
    PaperConference,
    Patent,
    Performance,
    Periodical,
    PersonalCommunication,
    Post,
    PostWeblog,
    Regulation,
    Report,
    Review,
    ReviewBook,
    Software,
    Song,
    Speech,
    Standard,
    Thesis,
    Treaty,
    Webpage,
}

impl Kind {
    pub fn from_citationberg_rs(x: &citationberg_rs::taxonomy::Kind) -> Self {
        return match x {
            citationberg_rs::taxonomy::Kind::Article => Kind::Article,
            citationberg_rs::taxonomy::Kind::ArticleJournal => Kind::ArticleJournal,
            citationberg_rs::taxonomy::Kind::ArticleMagazine => Kind::ArticleMagazine,
            citationberg_rs::taxonomy::Kind::ArticleNewspaper => Kind::ArticleNewspaper,
            citationberg_rs::taxonomy::Kind::Bill => Kind::Bill,
            citationberg_rs::taxonomy::Kind::Book => Kind::Book,
            citationberg_rs::taxonomy::Kind::Broadcast => Kind::Broadcast,
            citationberg_rs::taxonomy::Kind::Chapter => Kind::Chapter,
            citationberg_rs::taxonomy::Kind::Classic => Kind::Classic,
            citationberg_rs::taxonomy::Kind::Collection => Kind::Collection,
            citationberg_rs::taxonomy::Kind::Dataset => Kind::Dataset,
            citationberg_rs::taxonomy::Kind::Document => Kind::Document,
            citationberg_rs::taxonomy::Kind::Entry => Kind::Entry,
            citationberg_rs::taxonomy::Kind::EntryDictionary => Kind::EntryDictionary,
            citationberg_rs::taxonomy::Kind::EntryEncyclopedia => Kind::EntryEncyclopedia,
            citationberg_rs::taxonomy::Kind::Event => Kind::Event,
            citationberg_rs::taxonomy::Kind::Figure => Kind::Figure,
            citationberg_rs::taxonomy::Kind::Graphic => Kind::Graphic,
            citationberg_rs::taxonomy::Kind::Hearing => Kind::Hearing,
            citationberg_rs::taxonomy::Kind::Interview => Kind::Interview,
            citationberg_rs::taxonomy::Kind::LegalCase => Kind::LegalCase,
            citationberg_rs::taxonomy::Kind::Legislation => Kind::Legislation,
            citationberg_rs::taxonomy::Kind::Manuscript => Kind::Manuscript,
            citationberg_rs::taxonomy::Kind::Map => Kind::Map,
            citationberg_rs::taxonomy::Kind::MotionPicture => Kind::MotionPicture,
            citationberg_rs::taxonomy::Kind::MusicalScore => Kind::MusicalScore,
            citationberg_rs::taxonomy::Kind::Pamphlet => Kind::Pamphlet,
            citationberg_rs::taxonomy::Kind::PaperConference => Kind::PaperConference,
            citationberg_rs::taxonomy::Kind::Patent => Kind::Patent,
            citationberg_rs::taxonomy::Kind::Performance => Kind::Performance,
            citationberg_rs::taxonomy::Kind::Periodical => Kind::Periodical,
            citationberg_rs::taxonomy::Kind::PersonalCommunication => Kind::PersonalCommunication,
            citationberg_rs::taxonomy::Kind::Post => Kind::Post,
            citationberg_rs::taxonomy::Kind::PostWeblog => Kind::PostWeblog,
            citationberg_rs::taxonomy::Kind::Regulation => Kind::Regulation,
            citationberg_rs::taxonomy::Kind::Report => Kind::Report,
            citationberg_rs::taxonomy::Kind::Review => Kind::Review,
            citationberg_rs::taxonomy::Kind::ReviewBook => Kind::ReviewBook,
            citationberg_rs::taxonomy::Kind::Software => Kind::Software,
            citationberg_rs::taxonomy::Kind::Song => Kind::Song,
            citationberg_rs::taxonomy::Kind::Speech => Kind::Speech,
            citationberg_rs::taxonomy::Kind::Standard => Kind::Standard,
            citationberg_rs::taxonomy::Kind::Thesis => Kind::Thesis,
            citationberg_rs::taxonomy::Kind::Treaty => Kind::Treaty,
            citationberg_rs::taxonomy::Kind::Webpage => Kind::Webpage,
        };
    }
    pub fn to_citationberg_rs(&self) -> citationberg_rs::taxonomy::Kind {
        return match self {
            Kind::Article => citationberg_rs::taxonomy::Kind::Article,
            Kind::ArticleJournal => citationberg_rs::taxonomy::Kind::ArticleJournal,
            Kind::ArticleMagazine => citationberg_rs::taxonomy::Kind::ArticleMagazine,
            Kind::ArticleNewspaper => citationberg_rs::taxonomy::Kind::ArticleNewspaper,
            Kind::Bill => citationberg_rs::taxonomy::Kind::Bill,
            Kind::Book => citationberg_rs::taxonomy::Kind::Book,
            Kind::Broadcast => citationberg_rs::taxonomy::Kind::Broadcast,
            Kind::Chapter => citationberg_rs::taxonomy::Kind::Chapter,
            Kind::Classic => citationberg_rs::taxonomy::Kind::Classic,
            Kind::Collection => citationberg_rs::taxonomy::Kind::Collection,
            Kind::Dataset => citationberg_rs::taxonomy::Kind::Dataset,
            Kind::Document => citationberg_rs::taxonomy::Kind::Document,
            Kind::Entry => citationberg_rs::taxonomy::Kind::Entry,
            Kind::EntryDictionary => citationberg_rs::taxonomy::Kind::EntryDictionary,
            Kind::EntryEncyclopedia => citationberg_rs::taxonomy::Kind::EntryEncyclopedia,
            Kind::Event => citationberg_rs::taxonomy::Kind::Event,
            Kind::Figure => citationberg_rs::taxonomy::Kind::Figure,
            Kind::Graphic => citationberg_rs::taxonomy::Kind::Graphic,
            Kind::Hearing => citationberg_rs::taxonomy::Kind::Hearing,
            Kind::Interview => citationberg_rs::taxonomy::Kind::Interview,
            Kind::LegalCase => citationberg_rs::taxonomy::Kind::LegalCase,
            Kind::Legislation => citationberg_rs::taxonomy::Kind::Legislation,
            Kind::Manuscript => citationberg_rs::taxonomy::Kind::Manuscript,
            Kind::Map => citationberg_rs::taxonomy::Kind::Map,
            Kind::MotionPicture => citationberg_rs::taxonomy::Kind::MotionPicture,
            Kind::MusicalScore => citationberg_rs::taxonomy::Kind::MusicalScore,
            Kind::Pamphlet => citationberg_rs::taxonomy::Kind::Pamphlet,
            Kind::PaperConference => citationberg_rs::taxonomy::Kind::PaperConference,
            Kind::Patent => citationberg_rs::taxonomy::Kind::Patent,
            Kind::Performance => citationberg_rs::taxonomy::Kind::Performance,
            Kind::Periodical => citationberg_rs::taxonomy::Kind::Periodical,
            Kind::PersonalCommunication => citationberg_rs::taxonomy::Kind::PersonalCommunication,
            Kind::Post => citationberg_rs::taxonomy::Kind::Post,
            Kind::PostWeblog => citationberg_rs::taxonomy::Kind::PostWeblog,
            Kind::Regulation => citationberg_rs::taxonomy::Kind::Regulation,
            Kind::Report => citationberg_rs::taxonomy::Kind::Report,
            Kind::Review => citationberg_rs::taxonomy::Kind::Review,
            Kind::ReviewBook => citationberg_rs::taxonomy::Kind::ReviewBook,
            Kind::Software => citationberg_rs::taxonomy::Kind::Software,
            Kind::Song => citationberg_rs::taxonomy::Kind::Song,
            Kind::Speech => citationberg_rs::taxonomy::Kind::Speech,
            Kind::Standard => citationberg_rs::taxonomy::Kind::Standard,
            Kind::Thesis => citationberg_rs::taxonomy::Kind::Thesis,
            Kind::Treaty => citationberg_rs::taxonomy::Kind::Treaty,
            Kind::Webpage => citationberg_rs::taxonomy::Kind::Webpage,
        };
    }
}
