use citationberg;
use wasm_bindgen::prelude::*;

#[wasm_bindgen]
#[derive(Clone)]
pub enum Locator {
    Act,
    Appendix,
    ArticleLocator,
    Book,
    Canon,
    Chapter,
    Column,
    Elocation,
    Equation,
    Figure,
    Folio,
    Issue,
    Line,
    Note,
    Opus,
    Page,
    Paragraph,
    Part,
    Rule,
    Scene,
    Section,
    SubVerbo,
    Supplement,
    Table,
    Timestamp,
    Title,
    TitleLocator,
    Verse,
    Volume,
    Custom,
}
impl From<Locator> for citationberg::taxonomy::Locator {
    fn from(v: Locator) -> Self {
        match v {
            Locator::Act => Self::Act,
            Locator::Appendix => Self::Appendix,
            Locator::ArticleLocator => Self::ArticleLocator,
            Locator::Book => Self::Book,
            Locator::Canon => Self::Canon,
            Locator::Chapter => Self::Chapter,
            Locator::Column => Self::Column,
            Locator::Elocation => Self::Elocation,
            Locator::Equation => Self::Equation,
            Locator::Figure => Self::Figure,
            Locator::Folio => Self::Folio,
            Locator::Issue => Self::Issue,
            Locator::Line => Self::Line,
            Locator::Note => Self::Note,
            Locator::Opus => Self::Opus,
            Locator::Page => Self::Page,
            Locator::Paragraph => Self::Paragraph,
            Locator::Part => Self::Part,
            Locator::Rule => Self::Rule,
            Locator::Scene => Self::Scene,
            Locator::Section => Self::Section,
            Locator::SubVerbo => Self::SubVerbo,
            Locator::Supplement => Self::Supplement,
            Locator::Table => Self::Table,
            Locator::Timestamp => Self::Timestamp,
            Locator::Title => Self::Title,
            Locator::TitleLocator => Self::TitleLocator,
            Locator::Verse => Self::Verse,
            Locator::Volume => Self::Volume,
            Locator::Custom => Self::Custom,
        }
    }
}
impl From<citationberg::taxonomy::Locator> for Locator {
    fn from(v: citationberg::taxonomy::Locator) -> Self {
        match v {
            citationberg::taxonomy::Locator::Act => Self::Act,
            citationberg::taxonomy::Locator::Appendix => Self::Appendix,
            citationberg::taxonomy::Locator::ArticleLocator => Self::ArticleLocator,
            citationberg::taxonomy::Locator::Book => Self::Book,
            citationberg::taxonomy::Locator::Canon => Self::Canon,
            citationberg::taxonomy::Locator::Chapter => Self::Chapter,
            citationberg::taxonomy::Locator::Column => Self::Column,
            citationberg::taxonomy::Locator::Elocation => Self::Elocation,
            citationberg::taxonomy::Locator::Equation => Self::Equation,
            citationberg::taxonomy::Locator::Figure => Self::Figure,
            citationberg::taxonomy::Locator::Folio => Self::Folio,
            citationberg::taxonomy::Locator::Issue => Self::Issue,
            citationberg::taxonomy::Locator::Line => Self::Line,
            citationberg::taxonomy::Locator::Note => Self::Note,
            citationberg::taxonomy::Locator::Opus => Self::Opus,
            citationberg::taxonomy::Locator::Page => Self::Page,
            citationberg::taxonomy::Locator::Paragraph => Self::Paragraph,
            citationberg::taxonomy::Locator::Part => Self::Part,
            citationberg::taxonomy::Locator::Rule => Self::Rule,
            citationberg::taxonomy::Locator::Scene => Self::Scene,
            citationberg::taxonomy::Locator::Section => Self::Section,
            citationberg::taxonomy::Locator::SubVerbo => Self::SubVerbo,
            citationberg::taxonomy::Locator::Supplement => Self::Supplement,
            citationberg::taxonomy::Locator::Table => Self::Table,
            citationberg::taxonomy::Locator::Timestamp => Self::Timestamp,
            citationberg::taxonomy::Locator::Title => Self::Title,
            citationberg::taxonomy::Locator::TitleLocator => Self::TitleLocator,
            citationberg::taxonomy::Locator::Verse => Self::Verse,
            citationberg::taxonomy::Locator::Volume => Self::Volume,
            citationberg::taxonomy::Locator::Custom => Self::Custom,
        }
    }
}
