use crate::*;
use citationberg_rs;
use js_sys::*;
use wasm_bindgen::prelude::*;
use web_sys::*;

#[wasm_bindgen]
#[derive(Copy, Clone, Debug)]
pub enum OtherTerm {
    Month01,
    Month02,
    Month03,
    Month04,
    Month05,
    Month06,
    Month07,
    Month08,
    Month09,
    Month10,
    Month11,
    Month12,
    Ordinal,
    // OrdinalN(u8),
    // LongOrdinal(u8),
    OpenQuote,
    CloseQuote,
    OpenInnerQuote,
    CloseInnerQuote,
    PageRangeDelimiter,
    Colon,
    Comma,
    Semicolon,
    Season01,
    Season02,
    Season03,
    Season04,
    Anthropology,
    Astronomy,
    Biology,
    Botany,
    Chemistry,
    Engineering,
    GenericBase,
    Geography,
    Geology,
    History,
    Humanities,
    Literature,
    Math,
    Medicine,
    Philosophy,
    Physics,
    Psychology,
    Sociology,
    Science,
    PoliticalScience,
    SocialScience,
    Theology,
    Zoology,
    Accessed,
    Ad,
    AdvanceOnlinePublication,
    Album,
    And,
    AndOthers,
    Anonymous,
    At,
    AudioRecording,
    AvailableAt,
    Bc,
    Bce,
    By,
    Ce,
    Circa,
    Cited,
    EtAl,
    Film,
    Forthcoming,
    From,
    Henceforth,
    Ibid,
    In,
    InPress,
    Internet,
    Interview,
    Letter,
    LocCit,
    NoDate,
    NoPlace,
    NoPublisher,
    On,
    Online,
    OpCit,
    OriginalWorkPublished,
    PersonalCommunication,
    Podcast,
    PodcastEpisode,
    Preprint,
    PresentedAt,
    RadioBroadcast,
    RadioSeries,
    RadioSeriesEpisode,
    Reference,
    Retrieved,
    ReviewOf,
    Scale,
    SpecialIssue,
    SpecialSection,
    TelevisionBroadcast,
    TelevisionSeries,
    TelevisionSeriesEpisode,
    Video,
    WorkingPaper,
}

impl OtherTerm {
    pub fn from_citationberg_rs(x: &citationberg_rs::taxonomy::OtherTerm) -> Self {
        return match x {
            citationberg_rs::taxonomy::OtherTerm::Month01 => OtherTerm::Month01,
            citationberg_rs::taxonomy::OtherTerm::Month02 => OtherTerm::Month02,
            citationberg_rs::taxonomy::OtherTerm::Month03 => OtherTerm::Month03,
            citationberg_rs::taxonomy::OtherTerm::Month04 => OtherTerm::Month04,
            citationberg_rs::taxonomy::OtherTerm::Month05 => OtherTerm::Month05,
            citationberg_rs::taxonomy::OtherTerm::Month06 => OtherTerm::Month06,
            citationberg_rs::taxonomy::OtherTerm::Month07 => OtherTerm::Month07,
            citationberg_rs::taxonomy::OtherTerm::Month08 => OtherTerm::Month08,
            citationberg_rs::taxonomy::OtherTerm::Month09 => OtherTerm::Month09,
            citationberg_rs::taxonomy::OtherTerm::Month10 => OtherTerm::Month10,
            citationberg_rs::taxonomy::OtherTerm::Month11 => OtherTerm::Month11,
            citationberg_rs::taxonomy::OtherTerm::Month12 => OtherTerm::Month12,
            citationberg_rs::taxonomy::OtherTerm::Ordinal => OtherTerm::Ordinal,
            citationberg_rs::taxonomy::OtherTerm::OrdinalN(_) => todo!(),
            citationberg_rs::taxonomy::OtherTerm::LongOrdinal(_) => todo!(),
            citationberg_rs::taxonomy::OtherTerm::OpenQuote => OtherTerm::OpenQuote,
            citationberg_rs::taxonomy::OtherTerm::CloseQuote => OtherTerm::CloseQuote,
            citationberg_rs::taxonomy::OtherTerm::OpenInnerQuote => OtherTerm::OpenInnerQuote,
            citationberg_rs::taxonomy::OtherTerm::CloseInnerQuote => OtherTerm::CloseInnerQuote,
            citationberg_rs::taxonomy::OtherTerm::PageRangeDelimiter => {
                OtherTerm::PageRangeDelimiter
            }
            citationberg_rs::taxonomy::OtherTerm::Colon => OtherTerm::Colon,
            citationberg_rs::taxonomy::OtherTerm::Comma => OtherTerm::Comma,
            citationberg_rs::taxonomy::OtherTerm::Semicolon => OtherTerm::Semicolon,
            citationberg_rs::taxonomy::OtherTerm::Season01 => OtherTerm::Season01,
            citationberg_rs::taxonomy::OtherTerm::Season02 => OtherTerm::Season02,
            citationberg_rs::taxonomy::OtherTerm::Season03 => OtherTerm::Season03,
            citationberg_rs::taxonomy::OtherTerm::Season04 => OtherTerm::Season04,
            citationberg_rs::taxonomy::OtherTerm::Anthropology => OtherTerm::Anthropology,
            citationberg_rs::taxonomy::OtherTerm::Astronomy => OtherTerm::Astronomy,
            citationberg_rs::taxonomy::OtherTerm::Biology => OtherTerm::Biology,
            citationberg_rs::taxonomy::OtherTerm::Botany => OtherTerm::Botany,
            citationberg_rs::taxonomy::OtherTerm::Chemistry => OtherTerm::Chemistry,
            citationberg_rs::taxonomy::OtherTerm::Engineering => OtherTerm::Engineering,
            citationberg_rs::taxonomy::OtherTerm::GenericBase => OtherTerm::GenericBase,
            citationberg_rs::taxonomy::OtherTerm::Geography => OtherTerm::Geography,
            citationberg_rs::taxonomy::OtherTerm::Geology => OtherTerm::Geology,
            citationberg_rs::taxonomy::OtherTerm::History => OtherTerm::History,
            citationberg_rs::taxonomy::OtherTerm::Humanities => OtherTerm::Humanities,
            citationberg_rs::taxonomy::OtherTerm::Literature => OtherTerm::Literature,
            citationberg_rs::taxonomy::OtherTerm::Math => OtherTerm::Math,
            citationberg_rs::taxonomy::OtherTerm::Medicine => OtherTerm::Medicine,
            citationberg_rs::taxonomy::OtherTerm::Philosophy => OtherTerm::Philosophy,
            citationberg_rs::taxonomy::OtherTerm::Physics => OtherTerm::Physics,
            citationberg_rs::taxonomy::OtherTerm::Psychology => OtherTerm::Psychology,
            citationberg_rs::taxonomy::OtherTerm::Sociology => OtherTerm::Sociology,
            citationberg_rs::taxonomy::OtherTerm::Science => OtherTerm::Science,
            citationberg_rs::taxonomy::OtherTerm::PoliticalScience => OtherTerm::PoliticalScience,
            citationberg_rs::taxonomy::OtherTerm::SocialScience => OtherTerm::SocialScience,
            citationberg_rs::taxonomy::OtherTerm::Theology => OtherTerm::Theology,
            citationberg_rs::taxonomy::OtherTerm::Zoology => OtherTerm::Zoology,
            citationberg_rs::taxonomy::OtherTerm::Accessed => OtherTerm::Accessed,
            citationberg_rs::taxonomy::OtherTerm::Ad => OtherTerm::Ad,
            citationberg_rs::taxonomy::OtherTerm::AdvanceOnlinePublication => {
                OtherTerm::AdvanceOnlinePublication
            }
            citationberg_rs::taxonomy::OtherTerm::Album => OtherTerm::Album,
            citationberg_rs::taxonomy::OtherTerm::And => OtherTerm::And,
            citationberg_rs::taxonomy::OtherTerm::AndOthers => OtherTerm::AndOthers,
            citationberg_rs::taxonomy::OtherTerm::Anonymous => OtherTerm::Anonymous,
            citationberg_rs::taxonomy::OtherTerm::At => OtherTerm::At,
            citationberg_rs::taxonomy::OtherTerm::AudioRecording => OtherTerm::AudioRecording,
            citationberg_rs::taxonomy::OtherTerm::AvailableAt => OtherTerm::AvailableAt,
            citationberg_rs::taxonomy::OtherTerm::Bc => OtherTerm::Bc,
            citationberg_rs::taxonomy::OtherTerm::Bce => OtherTerm::Bce,
            citationberg_rs::taxonomy::OtherTerm::By => OtherTerm::By,
            citationberg_rs::taxonomy::OtherTerm::Ce => OtherTerm::Ce,
            citationberg_rs::taxonomy::OtherTerm::Circa => OtherTerm::Circa,
            citationberg_rs::taxonomy::OtherTerm::Cited => OtherTerm::Cited,
            citationberg_rs::taxonomy::OtherTerm::EtAl => OtherTerm::EtAl,
            citationberg_rs::taxonomy::OtherTerm::Film => OtherTerm::Film,
            citationberg_rs::taxonomy::OtherTerm::Forthcoming => OtherTerm::Forthcoming,
            citationberg_rs::taxonomy::OtherTerm::From => OtherTerm::From,
            citationberg_rs::taxonomy::OtherTerm::Henceforth => OtherTerm::Henceforth,
            citationberg_rs::taxonomy::OtherTerm::Ibid => OtherTerm::Ibid,
            citationberg_rs::taxonomy::OtherTerm::In => OtherTerm::In,
            citationberg_rs::taxonomy::OtherTerm::InPress => OtherTerm::InPress,
            citationberg_rs::taxonomy::OtherTerm::Internet => OtherTerm::Internet,
            citationberg_rs::taxonomy::OtherTerm::Interview => OtherTerm::Interview,
            citationberg_rs::taxonomy::OtherTerm::Letter => OtherTerm::Letter,
            citationberg_rs::taxonomy::OtherTerm::LocCit => OtherTerm::LocCit,
            citationberg_rs::taxonomy::OtherTerm::NoDate => OtherTerm::NoDate,
            citationberg_rs::taxonomy::OtherTerm::NoPlace => OtherTerm::NoPlace,
            citationberg_rs::taxonomy::OtherTerm::NoPublisher => OtherTerm::NoPublisher,
            citationberg_rs::taxonomy::OtherTerm::On => OtherTerm::On,
            citationberg_rs::taxonomy::OtherTerm::Online => OtherTerm::Online,
            citationberg_rs::taxonomy::OtherTerm::OpCit => OtherTerm::OpCit,
            citationberg_rs::taxonomy::OtherTerm::OriginalWorkPublished => {
                OtherTerm::OriginalWorkPublished
            }
            citationberg_rs::taxonomy::OtherTerm::PersonalCommunication => {
                OtherTerm::PersonalCommunication
            }
            citationberg_rs::taxonomy::OtherTerm::Podcast => OtherTerm::Podcast,
            citationberg_rs::taxonomy::OtherTerm::PodcastEpisode => OtherTerm::PodcastEpisode,
            citationberg_rs::taxonomy::OtherTerm::Preprint => OtherTerm::Preprint,
            citationberg_rs::taxonomy::OtherTerm::PresentedAt => OtherTerm::PresentedAt,
            citationberg_rs::taxonomy::OtherTerm::RadioBroadcast => OtherTerm::RadioBroadcast,
            citationberg_rs::taxonomy::OtherTerm::RadioSeries => OtherTerm::RadioSeries,
            citationberg_rs::taxonomy::OtherTerm::RadioSeriesEpisode => {
                OtherTerm::RadioSeriesEpisode
            }
            citationberg_rs::taxonomy::OtherTerm::Reference => OtherTerm::Reference,
            citationberg_rs::taxonomy::OtherTerm::Retrieved => OtherTerm::Retrieved,
            citationberg_rs::taxonomy::OtherTerm::ReviewOf => OtherTerm::ReviewOf,
            citationberg_rs::taxonomy::OtherTerm::Scale => OtherTerm::Scale,
            citationberg_rs::taxonomy::OtherTerm::SpecialIssue => OtherTerm::SpecialIssue,
            citationberg_rs::taxonomy::OtherTerm::SpecialSection => OtherTerm::SpecialSection,
            citationberg_rs::taxonomy::OtherTerm::TelevisionBroadcast => {
                OtherTerm::TelevisionBroadcast
            }
            citationberg_rs::taxonomy::OtherTerm::TelevisionSeries => OtherTerm::TelevisionSeries,
            citationberg_rs::taxonomy::OtherTerm::TelevisionSeriesEpisode => {
                OtherTerm::TelevisionSeriesEpisode
            }
            citationberg_rs::taxonomy::OtherTerm::Video => OtherTerm::Video,
            citationberg_rs::taxonomy::OtherTerm::WorkingPaper => OtherTerm::WorkingPaper,
        };
    }
    pub fn to_citationberg_rs(&self) -> citationberg_rs::taxonomy::OtherTerm {
        return match self {
            OtherTerm::Month01 => citationberg_rs::taxonomy::OtherTerm::Month01,
            OtherTerm::Month02 => citationberg_rs::taxonomy::OtherTerm::Month02,
            OtherTerm::Month03 => citationberg_rs::taxonomy::OtherTerm::Month03,
            OtherTerm::Month04 => citationberg_rs::taxonomy::OtherTerm::Month04,
            OtherTerm::Month05 => citationberg_rs::taxonomy::OtherTerm::Month05,
            OtherTerm::Month06 => citationberg_rs::taxonomy::OtherTerm::Month06,
            OtherTerm::Month07 => citationberg_rs::taxonomy::OtherTerm::Month07,
            OtherTerm::Month08 => citationberg_rs::taxonomy::OtherTerm::Month08,
            OtherTerm::Month09 => citationberg_rs::taxonomy::OtherTerm::Month09,
            OtherTerm::Month10 => citationberg_rs::taxonomy::OtherTerm::Month10,
            OtherTerm::Month11 => citationberg_rs::taxonomy::OtherTerm::Month11,
            OtherTerm::Month12 => citationberg_rs::taxonomy::OtherTerm::Month12,
            OtherTerm::Ordinal => citationberg_rs::taxonomy::OtherTerm::Ordinal,
            OtherTerm::OpenQuote => citationberg_rs::taxonomy::OtherTerm::OpenQuote,
            OtherTerm::CloseQuote => citationberg_rs::taxonomy::OtherTerm::CloseQuote,
            OtherTerm::OpenInnerQuote => citationberg_rs::taxonomy::OtherTerm::OpenInnerQuote,
            OtherTerm::CloseInnerQuote => citationberg_rs::taxonomy::OtherTerm::CloseInnerQuote,
            OtherTerm::PageRangeDelimiter => {
                citationberg_rs::taxonomy::OtherTerm::PageRangeDelimiter
            }
            OtherTerm::Colon => citationberg_rs::taxonomy::OtherTerm::Colon,
            OtherTerm::Comma => citationberg_rs::taxonomy::OtherTerm::Comma,
            OtherTerm::Semicolon => citationberg_rs::taxonomy::OtherTerm::Semicolon,
            OtherTerm::Season01 => citationberg_rs::taxonomy::OtherTerm::Season01,
            OtherTerm::Season02 => citationberg_rs::taxonomy::OtherTerm::Season02,
            OtherTerm::Season03 => citationberg_rs::taxonomy::OtherTerm::Season03,
            OtherTerm::Season04 => citationberg_rs::taxonomy::OtherTerm::Season04,
            OtherTerm::Anthropology => citationberg_rs::taxonomy::OtherTerm::Anthropology,
            OtherTerm::Astronomy => citationberg_rs::taxonomy::OtherTerm::Astronomy,
            OtherTerm::Biology => citationberg_rs::taxonomy::OtherTerm::Biology,
            OtherTerm::Botany => citationberg_rs::taxonomy::OtherTerm::Botany,
            OtherTerm::Chemistry => citationberg_rs::taxonomy::OtherTerm::Chemistry,
            OtherTerm::Engineering => citationberg_rs::taxonomy::OtherTerm::Engineering,
            OtherTerm::GenericBase => citationberg_rs::taxonomy::OtherTerm::GenericBase,
            OtherTerm::Geography => citationberg_rs::taxonomy::OtherTerm::Geography,
            OtherTerm::Geology => citationberg_rs::taxonomy::OtherTerm::Geology,
            OtherTerm::History => citationberg_rs::taxonomy::OtherTerm::History,
            OtherTerm::Humanities => citationberg_rs::taxonomy::OtherTerm::Humanities,
            OtherTerm::Literature => citationberg_rs::taxonomy::OtherTerm::Literature,
            OtherTerm::Math => citationberg_rs::taxonomy::OtherTerm::Math,
            OtherTerm::Medicine => citationberg_rs::taxonomy::OtherTerm::Medicine,
            OtherTerm::Philosophy => citationberg_rs::taxonomy::OtherTerm::Philosophy,
            OtherTerm::Physics => citationberg_rs::taxonomy::OtherTerm::Physics,
            OtherTerm::Psychology => citationberg_rs::taxonomy::OtherTerm::Psychology,
            OtherTerm::Sociology => citationberg_rs::taxonomy::OtherTerm::Sociology,
            OtherTerm::Science => citationberg_rs::taxonomy::OtherTerm::Science,
            OtherTerm::PoliticalScience => citationberg_rs::taxonomy::OtherTerm::PoliticalScience,
            OtherTerm::SocialScience => citationberg_rs::taxonomy::OtherTerm::SocialScience,
            OtherTerm::Theology => citationberg_rs::taxonomy::OtherTerm::Theology,
            OtherTerm::Zoology => citationberg_rs::taxonomy::OtherTerm::Zoology,
            OtherTerm::Accessed => citationberg_rs::taxonomy::OtherTerm::Accessed,
            OtherTerm::Ad => citationberg_rs::taxonomy::OtherTerm::Ad,
            OtherTerm::AdvanceOnlinePublication => {
                citationberg_rs::taxonomy::OtherTerm::AdvanceOnlinePublication
            }
            OtherTerm::Album => citationberg_rs::taxonomy::OtherTerm::Album,
            OtherTerm::And => citationberg_rs::taxonomy::OtherTerm::And,
            OtherTerm::AndOthers => citationberg_rs::taxonomy::OtherTerm::AndOthers,
            OtherTerm::Anonymous => citationberg_rs::taxonomy::OtherTerm::Anonymous,
            OtherTerm::At => citationberg_rs::taxonomy::OtherTerm::At,
            OtherTerm::AudioRecording => citationberg_rs::taxonomy::OtherTerm::AudioRecording,
            OtherTerm::AvailableAt => citationberg_rs::taxonomy::OtherTerm::AvailableAt,
            OtherTerm::Bc => citationberg_rs::taxonomy::OtherTerm::Bc,
            OtherTerm::Bce => citationberg_rs::taxonomy::OtherTerm::Bce,
            OtherTerm::By => citationberg_rs::taxonomy::OtherTerm::By,
            OtherTerm::Ce => citationberg_rs::taxonomy::OtherTerm::Ce,
            OtherTerm::Circa => citationberg_rs::taxonomy::OtherTerm::Circa,
            OtherTerm::Cited => citationberg_rs::taxonomy::OtherTerm::Cited,
            OtherTerm::EtAl => citationberg_rs::taxonomy::OtherTerm::EtAl,
            OtherTerm::Film => citationberg_rs::taxonomy::OtherTerm::Film,
            OtherTerm::Forthcoming => citationberg_rs::taxonomy::OtherTerm::Forthcoming,
            OtherTerm::From => citationberg_rs::taxonomy::OtherTerm::From,
            OtherTerm::Henceforth => citationberg_rs::taxonomy::OtherTerm::Henceforth,
            OtherTerm::Ibid => citationberg_rs::taxonomy::OtherTerm::Ibid,
            OtherTerm::In => citationberg_rs::taxonomy::OtherTerm::In,
            OtherTerm::InPress => citationberg_rs::taxonomy::OtherTerm::InPress,
            OtherTerm::Internet => citationberg_rs::taxonomy::OtherTerm::Internet,
            OtherTerm::Interview => citationberg_rs::taxonomy::OtherTerm::Interview,
            OtherTerm::Letter => citationberg_rs::taxonomy::OtherTerm::Letter,
            OtherTerm::LocCit => citationberg_rs::taxonomy::OtherTerm::LocCit,
            OtherTerm::NoDate => citationberg_rs::taxonomy::OtherTerm::NoDate,
            OtherTerm::NoPlace => citationberg_rs::taxonomy::OtherTerm::NoPlace,
            OtherTerm::NoPublisher => citationberg_rs::taxonomy::OtherTerm::NoPublisher,
            OtherTerm::On => citationberg_rs::taxonomy::OtherTerm::On,
            OtherTerm::Online => citationberg_rs::taxonomy::OtherTerm::Online,
            OtherTerm::OpCit => citationberg_rs::taxonomy::OtherTerm::OpCit,
            OtherTerm::OriginalWorkPublished => {
                citationberg_rs::taxonomy::OtherTerm::OriginalWorkPublished
            }
            OtherTerm::PersonalCommunication => {
                citationberg_rs::taxonomy::OtherTerm::PersonalCommunication
            }
            OtherTerm::Podcast => citationberg_rs::taxonomy::OtherTerm::Podcast,
            OtherTerm::PodcastEpisode => citationberg_rs::taxonomy::OtherTerm::PodcastEpisode,
            OtherTerm::Preprint => citationberg_rs::taxonomy::OtherTerm::Preprint,
            OtherTerm::PresentedAt => citationberg_rs::taxonomy::OtherTerm::PresentedAt,
            OtherTerm::RadioBroadcast => citationberg_rs::taxonomy::OtherTerm::RadioBroadcast,
            OtherTerm::RadioSeries => citationberg_rs::taxonomy::OtherTerm::RadioSeries,
            OtherTerm::RadioSeriesEpisode => {
                citationberg_rs::taxonomy::OtherTerm::RadioSeriesEpisode
            }
            OtherTerm::Reference => citationberg_rs::taxonomy::OtherTerm::Reference,
            OtherTerm::Retrieved => citationberg_rs::taxonomy::OtherTerm::Retrieved,
            OtherTerm::ReviewOf => citationberg_rs::taxonomy::OtherTerm::ReviewOf,
            OtherTerm::Scale => citationberg_rs::taxonomy::OtherTerm::Scale,
            OtherTerm::SpecialIssue => citationberg_rs::taxonomy::OtherTerm::SpecialIssue,
            OtherTerm::SpecialSection => citationberg_rs::taxonomy::OtherTerm::SpecialSection,
            OtherTerm::TelevisionBroadcast => {
                citationberg_rs::taxonomy::OtherTerm::TelevisionBroadcast
            }
            OtherTerm::TelevisionSeries => citationberg_rs::taxonomy::OtherTerm::TelevisionSeries,
            OtherTerm::TelevisionSeriesEpisode => {
                citationberg_rs::taxonomy::OtherTerm::TelevisionSeriesEpisode
            }
            OtherTerm::Video => citationberg_rs::taxonomy::OtherTerm::Video,
            OtherTerm::WorkingPaper => citationberg_rs::taxonomy::OtherTerm::WorkingPaper,
        };
    }

    pub fn from_u32(x: u32) -> Self {
        return match x {
            1 => OtherTerm::Month01,
            2 => OtherTerm::Month02,
            3 => OtherTerm::Month03,
            4 => OtherTerm::Month04,
            5 => OtherTerm::Month05,
            6 => OtherTerm::Month06,
            7 => OtherTerm::Month07,
            8 => OtherTerm::Month08,
            9 => OtherTerm::Month09,
            10 => OtherTerm::Month10,
            11 => OtherTerm::Month11,
            12 => OtherTerm::Month12,
            13 => OtherTerm::Ordinal,
            // OrdinalN(u8),
            // LongOrdinal(u8),
            14 => OtherTerm::OpenQuote,
            15 => OtherTerm::CloseQuote,
            16 => OtherTerm::OpenInnerQuote,
            17 => OtherTerm::CloseInnerQuote,
            18 => OtherTerm::PageRangeDelimiter,
            19 => OtherTerm::Colon,
            20 => OtherTerm::Comma,
            21 => OtherTerm::Semicolon,
            22 => OtherTerm::Season01,
            23 => OtherTerm::Season02,
            24 => OtherTerm::Season03,
            25 => OtherTerm::Season04,
            26 => OtherTerm::Anthropology,
            27 => OtherTerm::Astronomy,
            28 => OtherTerm::Biology,
            29 => OtherTerm::Botany,
            30 => OtherTerm::Chemistry,
            31 => OtherTerm::Engineering,
            32 => OtherTerm::GenericBase,
            33 => OtherTerm::Geography,
            34 => OtherTerm::Geology,
            35 => OtherTerm::History,
            36 => OtherTerm::Humanities,
            37 => OtherTerm::Literature,
            38 => OtherTerm::Math,
            39 => OtherTerm::Medicine,
            40 => OtherTerm::Philosophy,
            41 => OtherTerm::Physics,
            42 => OtherTerm::Psychology,
            43 => OtherTerm::Sociology,
            44 => OtherTerm::Science,
            45 => OtherTerm::PoliticalScience,
            46 => OtherTerm::SocialScience,
            47 => OtherTerm::Theology,
            48 => OtherTerm::Zoology,
            49 => OtherTerm::Accessed,
            50 => OtherTerm::Ad,
            51 => OtherTerm::AdvanceOnlinePublication,
            52 => OtherTerm::Album,
            53 => OtherTerm::And,
            54 => OtherTerm::AndOthers,
            55 => OtherTerm::Anonymous,
            56 => OtherTerm::At,
            57 => OtherTerm::AudioRecording,
            58 => OtherTerm::AvailableAt,
            59 => OtherTerm::Bc,
            60 => OtherTerm::Bce,
            61 => OtherTerm::By,
            62 => OtherTerm::Ce,
            63 => OtherTerm::Circa,
            64 => OtherTerm::Cited,
            65 => OtherTerm::EtAl,
            66 => OtherTerm::Film,
            67 => OtherTerm::Forthcoming,
            68 => OtherTerm::From,
            69 => OtherTerm::Henceforth,
            70 => OtherTerm::Ibid,
            71 => OtherTerm::In,
            72 => OtherTerm::InPress,
            73 => OtherTerm::Internet,
            74 => OtherTerm::Interview,
            75 => OtherTerm::Letter,
            76 => OtherTerm::LocCit,
            77 => OtherTerm::NoDate,
            78 => OtherTerm::NoPlace,
            79 => OtherTerm::NoPublisher,
            80 => OtherTerm::On,
            81 => OtherTerm::Online,
            82 => OtherTerm::OpCit,
            83 => OtherTerm::OriginalWorkPublished,
            84 => OtherTerm::PersonalCommunication,
            85 => OtherTerm::Podcast,
            86 => OtherTerm::PodcastEpisode,
            87 => OtherTerm::Preprint,
            88 => OtherTerm::PresentedAt,
            89 => OtherTerm::RadioBroadcast,
            90 => OtherTerm::RadioSeries,
            91 => OtherTerm::RadioSeriesEpisode,
            92 => OtherTerm::Reference,
            93 => OtherTerm::Retrieved,
            94 => OtherTerm::ReviewOf,
            95 => OtherTerm::Scale,
            96 => OtherTerm::SpecialIssue,
            97 => OtherTerm::SpecialSection,
            98 => OtherTerm::TelevisionBroadcast,
            99 => OtherTerm::TelevisionSeries,
            100 => OtherTerm::TelevisionSeriesEpisode,
            101 => OtherTerm::Video,
            102 => OtherTerm::WorkingPaper,
            _ => panic!("OtherTerm::from_u32: Invalid value"),
        };
    }
}

// TODO: Enum with data https://github.com/rustwasm/wasm-bindgen/issues/2407

#[wasm_bindgen]
#[allow(non_snake_case)]
pub fn OtherTerm_is_n_ordinal(x: u32) -> bool {
    let v = OtherTerm::from_u32(x);
    return match v {
        _ => false,
    };
}

#[wasm_bindgen]
#[allow(non_snake_case)]
pub fn OtherTerm_is_ordinal(x: u32) -> bool {
    let v = OtherTerm::from_u32(x);
    return match v {
        OtherTerm::Ordinal => true,
        _ => false,
    };
}

#[wasm_bindgen]
#[allow(non_snake_case)]
pub fn OtherTerm_month(x: u8) -> Option<OtherTerm> {
    return match x {
        0 => Some(OtherTerm::Month01),
        1 => Some(OtherTerm::Month02),
        2 => Some(OtherTerm::Month03),
        3 => Some(OtherTerm::Month04),
        4 => Some(OtherTerm::Month05),
        5 => Some(OtherTerm::Month06),
        6 => Some(OtherTerm::Month07),
        7 => Some(OtherTerm::Month08),
        8 => Some(OtherTerm::Month09),
        9 => Some(OtherTerm::Month10),
        10 => Some(OtherTerm::Month11),
        11 => Some(OtherTerm::Month12),
        _ => None,
    };
}

#[wasm_bindgen]
#[allow(non_snake_case)]
pub fn OtherTerm_season(x: u8) -> Option<OtherTerm> {
    return match x {
        0 => Some(OtherTerm::Season01),
        1 => Some(OtherTerm::Season02),
        2 => Some(OtherTerm::Season03),
        3 => Some(OtherTerm::Season04),
        _ => None,
    };
}
