use crate::macros::my_parallel_enum;
use citationberg;
use wasm_bindgen::prelude::*;

my_parallel_enum!(StandardVariable, citationberg::taxonomy::StandardVariable, {
    Abstract,
    Annote,
    Archive,
    ArchiveCollection,
    ArchiveLocation,
    ArchivePlace,
    Authority,
    CallNumber,
    CitationKey,
    CitationLabel,
    CollectionTitle,
    ContainerTitle,
    ContainerTitleShort,
    Dimensions,
    Division,
    DOI,
    Event,
    EventTitle,
    EventPlace,
    Genre,
    ISBN,
    ISSN,
    Jurisdiction,
    Keyword,
    Language,
    License,
    Medium,
    Note,
    OriginalPublisher,
    OriginalPublisherPlace,
    OriginalTitle,
    PartTitle,
    PMCID,
    PMID,
    Publisher,
    PublisherPlace,
    References,
    ReviewedGenre,
    ReviewedTitle,
    Scale,
    Source,
    Status,
    Title,
    TitleShort,
    URL,
    VolumeTitle,
    YearSuffix,
});
