[package]
name = "citationberg-wbg"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["start"]
start = []

[dependencies]
wasm-bindgen = "0.2.84"

[profile.release]
opt-level = "s"
